profiling: add tool path settings in project properity for profiling
eclipse-linuxtools/org.eclipse.linuxtools pull request #205
Opened 2023-06-27 03:41 UTC by laomaolaile

Try to resolve issue #181

2023-06-27 17:51 UTC, jjohnstn commented
Hello @laomaolaile To inevitably get this accepted you will need to sign the Eclipse Contributor Agreement for the e-mail you have attached to your github id.  Details can be found here: https://www.eclipse.org/legal/ECA.php  You will need to create an Eclipse account first if you haven't already.

2023-06-29 23:03 UTC, jjohnstn requested changes
Looks good.  A few issues to resolve which I have commented.

2023-06-29 23:05 UTC, jjohnstn commented
Test results are expected with rpm and createrepo tests.  These are being removed.

2023-07-06 00:13 UTC, jjohnstn commented
@laomaolaile If you can get the requested changes in before Tuesday of next week, your patch can get into 2023-09 M1.  Otherwise, it will have to wait until 2023-09 M2.

2023-07-06 01:39 UTC, laomaolaile commented
@jjohnstn  Okay, I'll finish it this week

2023-07-06 17:51 UTC, jjohnstn commented on profiling/org.eclipse.linuxtools.tools.launch.core/src/org/eclipse/linuxtools/tools/launch/core/factory/LinuxtoolsProcessFactory.java
> +	private static final String SEPARATOR_WIN32 = ";"; //$NON-NLS-1$
Looks good now.

2023-07-06 17:52 UTC, jjohnstn commented on profiling/org.eclipse.linuxtools.tools.launch.ui/src/org/eclipse/linuxtools/internal/tools/launch/ui/properties/messages.properties
> +LINUXTOOLS_PREFIX_TOOLTIP=Add extra prefix to command such as gcov addr2line nm c++filt strings gprof, eg, prefix riscv-nuclei-elf-, command, strings will be riscv-nuclei-elf-strings
Change looks good.

2023-07-06 17:54 UTC, jjohnstn approved these changes

2023-07-06 17:55 UTC, jjohnstn commented
Test failures have nothing to do with this patch.

2023-07-06 17:57 UTC, merged

2023-07-06 17:57 UTC, jjohnstn commented
Thanks @laomaolaile

2023-07-07 02:10 UTC, fanghuaqi commented
@laomaolaile You are using tab not spaces to indent code, and I found similar lines need to be adjusted. Maybe a new patch could be added to solve this

![image](https://github.com/eclipse-linuxtools/org.eclipse.linuxtools/assets/1538922/87f49ef1-0dda-4fc5-abe7-ddae2ff7f518)
![image](https://github.com/eclipse-linuxtools/org.eclipse.linuxtools/assets/1538922/af678933-d38f-4ae3-b6b4-980ed80e2c2a)
![image](https://github.com/eclipse-linuxtools/org.eclipse.linuxtools/assets/1538922/21a001c3-4143-45d6-80e9-f5fd2e4feb91)

2023-07-07 19:02 UTC, jjohnstn commented
@fanghuaqi Yes, he has used tabs which actually is the right way to do it.  The old code needs to be reformatted.  I noticed this in reviewing but did not want extra reformatting along with the patch as it obfuscates the actual changes.  Another formatting patch is required.  I was going to do it prior to 2023-09 M1, but feel free if you wish.